services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-development
    image: blog_api_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
      - elasticsearch

  nginx:
    image: nginx:alpine
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-blog_api}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      retries: 5
      timeout: 5s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
    driver: local
